// frontend/src/app/(auth)/register/page.tsx
"use client";

import { useState } from "react";
import Link from "next/link";
import { useAuth } from "@/hooks/use-auth";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { CheckSquare } from "lucide-react";

export default function RegisterPage() {
  const [fullName, setFullName] = useState("");
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [confirmPassword, setConfirmPassword] = useState("");
  const [validationError, setValidationError] = useState<string | null>(null);

  const { register, isLoading, error: authError } = useAuth();

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setValidationError(null);

    if (password !== confirmPassword) {
      setValidationError("Passwords do not match");
      return;
    }

    await register(email, password, fullName);
  };

  const error = validationError || authError;

  return (
    <div className="flex min-h-screen items-center justify-center bg-gray-50 px-4">
      <div className="w-full max-w-md space-y-8 rounded-xl border border-gray-200 bg-white p-8 shadow-sm">
        <div className="flex flex-col items-center text-center">
          <div className="mb-4 flex h-12 w-12 items-center justify-center rounded-full bg-blue-100">
            <CheckSquare className="h-6 w-6 text-blue-600" />
          </div>
          <h2 className="text-2xl font-bold tracking-tight text-gray-900">
            Create an account
          </h2>
          <p className="mt-2 text-sm text-gray-500">
            Enter your details below to get started
          </p>
        </div>

        <form className="mt-8 space-y-6" onSubmit={handleSubmit}>
          <div className="space-y-4">
            <div className="grid gap-2">
              <Label htmlFor="fullName">Full Name</Label>
              <Input
                id="fullName"
                placeholder="John Doe"
                type="text"
                disabled={isLoading}
                value={fullName}
                onChange={(e) => setFullName(e.target.value)}
                required
              />
            </div>
            <div className="grid gap-2">
              <Label htmlFor="email">Email</Label>
              <Input
                id="email"
                placeholder="name@example.com"
                type="email"
                autoComplete="email"
                disabled={isLoading}
                value={email}
                onChange={(e) => setEmail(e.target.value)}
                required
              />
            </div>
            <div className="grid gap-2">
              <Label htmlFor="password">Password</Label>
              <Input
                id="password"
                placeholder="••••••••"
                type="password"
                autoComplete="new-password"
                disabled={isLoading}
                minLength={8}
                value={password}
                onChange={(e) => setPassword(e.target.value)}
                required
              />
            </div>
            <div className="grid gap-2">
              <Label htmlFor="confirmPassword">Confirm Password</Label>
              <Input
                id="confirmPassword"
                placeholder="••••••••"
                type="password"
                autoComplete="new-password"
                disabled={isLoading}
                value={confirmPassword}
                onChange={(e) => setConfirmPassword(e.target.value)}
                required
              />
            </div>
          </div>

          {error && (
            <div className="rounded-md border border-red-200 bg-red-50 p-3 text-sm font-medium text-red-600">
              {error}
            </div>
          )}

          <Button disabled={isLoading} isLoading={isLoading} className="w-full">
            Sign Up
          </Button>
        </form>

        <div className="text-center text-sm">
          <span className="text-gray-500">Already have an account? </span>
          <Link
            href="/login"
            className="font-medium text-blue-600 hover:text-blue-500 hover:underline"
          >
            Log in
          </Link>
        </div>
      </div>
    </div>
  );
}

// frontend/app/pages/register.vue
<script setup lang="ts">
import { CheckSquare } from "lucide-vue-next";

definePageMeta({
  layout: false,
});

const fullName = ref("");
const email = ref("");
const password = ref("");
const confirmPassword = ref("");
const validationError = ref<string | null>(null);

const { register, isLoading, error: authError } = useAuth();

const handleSubmit = async () => {
  validationError.value = null;

  if (password.value !== confirmPassword.value) {
    validationError.value = "Passwords do not match";
    return;
  }

  await register(email.value, password.value, fullName.value);
};

const error = computed(() => validationError.value || authError.value);
</script>

<template>
  <div class="bg-background flex min-h-screen items-center justify-center px-4">
    <div class="absolute top-4 right-4">
      <LayoutThemeToggle />
    </div>
    <div
      class="border-border bg-card w-full max-w-md space-y-8 rounded-xl border p-8 shadow-sm"
    >
      <div class="flex flex-col items-center text-center">
        <div
          class="bg-primary/10 mb-4 flex h-12 w-12 items-center justify-center rounded-full"
        >
          <CheckSquare class="text-primary h-6 w-6" />
        </div>
        <h2 class="text-card-foreground text-2xl font-bold tracking-tight">
          Create an account
        </h2>
        <p class="text-muted-foreground mt-2 text-sm">
          Enter your details below to get started
        </p>
      </div>

      <form class="mt-8 space-y-6" @submit.prevent="handleSubmit">
        <div class="space-y-4">
          <div class="grid gap-2">
            <UiBaseLabel for="fullName">Full Name</UiBaseLabel>
            <UiBaseInput
              id="fullName"
              v-model="fullName"
              placeholder="John Doe"
              type="text"
              required
              :disabled="isLoading"
            />
          </div>
          <div class="grid gap-2">
            <UiBaseLabel for="email">Email</UiBaseLabel>
            <UiBaseInput
              id="email"
              v-model="email"
              placeholder="name@example.com"
              type="email"
              auto-complete="email"
              required
              :disabled="isLoading"
            />
          </div>
          <div class="grid gap-2">
            <UiBaseLabel for="password">Password</UiBaseLabel>
            <UiBaseInput
              id="password"
              v-model="password"
              placeholder="••••••••"
              type="password"
              auto-complete="new-password"
              required
              min-length="8"
              :disabled="isLoading"
            />
          </div>
          <div class="grid gap-2">
            <UiBaseLabel for="confirmPassword">Confirm Password</UiBaseLabel>
            <UiBaseInput
              id="confirmPassword"
              v-model="confirmPassword"
              placeholder="••••••••"
              type="password"
              auto-complete="new-password"
              required
              :disabled="isLoading"
            />
          </div>
        </div>

        <div
          v-if="error"
          class="border-destructive/50 bg-destructive/10 text-destructive rounded-md border p-3 text-sm font-medium"
        >
          {{ error }}
        </div>

        <UiBaseButton :disabled="isLoading" class="w-full">
          {{ isLoading ? "Creating Account..." : "Sign Up" }}
        </UiBaseButton>
      </form>

      <div class="text-center text-sm">
        <span class="text-muted-foreground">Already have an account? </span>
        <NuxtLink
          to="/login"
          class="text-primary hover:text-primary/80 font-medium hover:underline"
        >
          Log in
        </NuxtLink>
      </div>
    </div>
  </div>
</template>
