// frontend/src/components/tasks/comment-item.tsx
"use client";

import { Avatar } from "@/components/ui/avatar";
import { formatDistanceToNow } from "date-fns";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import { Comment } from "@/types";

interface CommentItemProps {
  comment: Comment;
  currentUserId?: number;
  onDelete?: (id: number) => void;
}

export function CommentItem({
  comment,
  currentUserId,
  onDelete,
}: CommentItemProps) {
  const author = comment.author || {
    id: 0,
    email: "unknown@user.com",
    full_name: "Unknown User",
  };
  const authorName = author.full_name || author.email.split("@")[0];
  const initial = (author.full_name || author.email)[0].toUpperCase();
  const isAuthor = currentUserId === author.id;

  return (
    <div className="group flex gap-4">
      <Avatar
        fallback={initial}
        className="mt-1 h-10 w-10 border border-gray-100 shadow-sm"
      />
      <div className="min-w-0 flex-1">
        <div className="mb-1 flex items-center justify-between">
          <div className="flex items-center gap-2">
            <span className="cursor-pointer text-sm font-semibold text-gray-900 hover:underline">
              {authorName}
            </span>
            <span className="text-xs text-gray-500">
              commented {formatDistanceToNow(new Date(comment.created_at))} ago
            </span>
          </div>
          {isAuthor && onDelete && (
            <button
              onClick={() => onDelete(comment.id)}
              className="text-xs text-gray-400 opacity-0 transition-opacity group-hover:opacity-100 hover:text-red-600"
            >
              Delete
            </button>
          )}
        </div>
        <div className="prose prose-sm prose-pre:bg-gray-50 prose-pre:border prose-pre:border-gray-100 max-w-none rounded-lg border border-gray-200 bg-white p-4 shadow-sm">
          <ReactMarkdown remarkPlugins={[remarkGfm]}>
            {comment.content}
          </ReactMarkdown>
        </div>
      </div>
    </div>
  );
}

// frontend/app/components/tasks/CommentItem.vue
<script setup lang="ts">
import { formatDistanceToNow } from "date-fns";
import VueMarkdown from "vue-markdown-render";
import type { Comment } from "~/types";

interface Props {
  comment: Comment;
  currentUserId?: string;
}

const { comment, currentUserId = "" } = defineProps<Props>();

const emit = defineEmits(["delete"]);

const author = computed(
  () =>
    comment.author || {
      id: "",
      email: "unknown@user.com",
      full_name: "Unknown User",
    }
);

const authorName = computed(
  () => author.value.full_name || author.value.email.split("@")[0]
);
const initial = computed(() =>
  (author.value.full_name || author.value.email)[0].toUpperCase()
);
const isAuthor = computed(() => currentUserId === author.value.id);
</script>

<template>
  <div class="group flex gap-4">
    <UiBaseAvatar
      :fallback="initial"
      class-name="mt-1 h-10 w-10 border border-gray-100 shadow-sm"
    />
    <div class="min-w-0 flex-1">
      <div class="mb-1 flex items-center justify-between">
        <div class="flex items-center gap-2">
          <span
            class="cursor-pointer text-sm font-semibold text-gray-900 hover:underline"
          >
            {{ authorName }}
          </span>
          <span class="text-xs text-gray-500">
            commented
            {{ formatDistanceToNow(new Date(comment.created_at)) }} ago
          </span>
        </div>
        <button
          v-if="isAuthor"
          class="text-xs text-gray-400 opacity-0 transition-opacity group-hover:opacity-100 hover:text-red-600"
          @click="emit('delete', comment.id)"
        >
          Delete
        </button>
      </div>
      <VueMarkdown
        :source="comment.content"
        class="prose prose-sm prose-pre:bg-gray-50 prose-pre:border prose-pre:border-gray-100 max-w-none rounded-lg border border-gray-200 bg-white p-4 shadow-sm"
      />
    </div>
  </div>
</template>
