// nuxt-app/app/components/tasks/selectors/AssigneeSelector.vue
<script setup lang="ts">
import {
  Listbox,
  ListboxButton,
  ListboxOptions,
  ListboxOption,
  TransitionRoot,
} from "@headlessui/vue";
import { Check, ChevronsUpDown, User as UserIcon } from "lucide-vue-next";
import type { ProjectMember } from "~/types";

interface Props {
  members?: ProjectMember[];
  modelValue?: number | null;
  disabled?: boolean;
}

const {
  members = [],
  modelValue = null,
  disabled = false,
} = defineProps<Props>();
const emit = defineEmits(["update:modelValue", "change"]);

const selected = computed(
  () => members.find((m) => m.user_id === modelValue) || null
);

const handleChange = (value: number | null) => {
  emit("update:modelValue", value);
  emit("change", value);
};
</script>

<template>
  <Listbox
    :model-value="modelValue"
    :disabled="disabled"
    @update:model-value="handleChange"
  >
    <div class="relative mt-1">
      <ListboxButton
        class="relative w-full cursor-default rounded-md border border-gray-200 bg-white py-2 pr-10 pl-3 text-left text-sm focus:outline-none focus-visible:ring-2 focus-visible:ring-blue-500 focus-visible:ring-offset-2 sm:text-sm"
      >
        <span class="flex items-center gap-2 truncate">
          <UiBaseAvatar
            v-if="selected"
            :fallback="selected.email[0].toUpperCase() || '?'"
            class-name="h-5 w-5"
          />
          <UserIcon v-else class="h-4 w-4 text-gray-400" />
          <span class="block truncate">
            {{ selected ? selected.email : "Unassigned" }}
          </span>
        </span>
        <span
          class="pointer-events-none absolute inset-y-0 right-0 flex items-center pr-2"
        >
          <ChevronsUpDown class="h-4 w-4 text-gray-400" aria-hidden="true" />
        </span>
      </ListboxButton>

      <TransitionRoot
        leave="transition ease-in duration-100"
        leave-from="opacity-100"
        leave-to="opacity-0"
      >
        <ListboxOptions
          class="absolute z-50 mt-1 max-h-60 w-full overflow-auto rounded-md bg-white py-1 text-base shadow-lg ring-1 ring-black/5 focus:outline-none sm:text-sm"
        >
          <ListboxOption
            v-slot="{ active, selected: isSelected }"
            :value="null"
            as="template"
          >
            <li
              :class="[
                active ? 'bg-blue-50 text-blue-900' : 'text-gray-900',
                'relative cursor-default select-none py-2 pr-10 pl-10',
              ]"
            >
              <span class="flex items-center gap-2">
                <UserIcon class="h-4 w-4 text-gray-400" />
                <span
                  :class="[
                    !isSelected ? 'font-medium' : 'font-normal',
                    'block truncate',
                  ]"
                >
                  Unassigned
                </span>
              </span>
              <span
                v-if="!modelValue"
                class="absolute inset-y-0 left-0 flex items-center pl-3 text-blue-600"
              >
                <Check class="h-4 w-4" aria-hidden="true" />
              </span>
            </li>
          </ListboxOption>

          <ListboxOption
            v-for="member in members"
            :key="member.user_id"
            v-slot="{ active, selected: isSelected }"
            :value="member.user_id"
            as="template"
          >
            <li
              :class="[
                active ? 'bg-blue-50 text-blue-900' : 'text-gray-900',
                'relative cursor-default select-none py-2 pr-10 pl-10',
              ]"
            >
              <span class="flex items-center gap-2">
                <UiBaseAvatar
                  :fallback="member.email[0].toUpperCase() || '?'"
                  class-name="h-5 w-5"
                />
                <span
                  :class="[
                    isSelected ? 'font-medium' : 'font-normal',
                    'block truncate',
                  ]"
                >
                  {{ member.email }}
                </span>
              </span>
              <span
                v-if="isSelected"
                class="absolute inset-y-0 left-0 flex items-center pl-3 text-blue-600"
              >
                <Check class="h-4 w-4" aria-hidden="true" />
              </span>
            </li>
          </ListboxOption>
        </ListboxOptions>
      </TransitionRoot>
    </div>
  </Listbox>
</template>

// frontend/src/components/tasks/selectors/assignee-selector.tsx
"use client";

import { useState, useRef } from "react";
import { Command } from "cmdk";
import { Check, ChevronsUpDown, User as UserIcon, Search } from "lucide-react";
import { cn } from "@/lib/utils";
import { useClickOutside } from "@/hooks/use-click-outside";
import { Avatar } from "@/components/ui/avatar";
import { ProjectMember } from "@/types";

interface AssigneeSelectorProps {
  members: ProjectMember[];
  value?: number;
  onChange: (value: number | undefined) => void;
}

export function AssigneeSelector({
  members,
  value,
  onChange,
}: AssigneeSelectorProps) {
  const [open, setOpen] = useState(false);
  const ref = useRef<HTMLDivElement>(null);

  useClickOutside(ref, () => setOpen(false));

  const selectedMember = members.find((m) => m.user_id === value);

  return (
    <div className="relative w-full" ref={ref}>
      <button
        type="button"
        onClick={() => setOpen(!open)}
        className={cn(
          "flex w-full items-center justify-between rounded-md border border-gray-200 bg-white px-3 py-2 text-sm ring-offset-white transition-colors placeholder:text-gray-500 hover:bg-gray-50 focus:ring-2 focus:ring-blue-500 focus:outline-none disabled:cursor-not-allowed disabled:opacity-50",
          !value && "text-gray-500"
        )}
      >
        <div className="flex min-w-0 flex-1 items-center gap-2">
          {selectedMember ? (
            <>
              <Avatar
                fallback={selectedMember.email[0].toUpperCase()}
                className="h-5 w-5 shrink-0 bg-blue-100 text-[10px]"
              />
              <span className="truncate">{selectedMember.email}</span>
            </>
          ) : (
            <>
              <div className="flex h-5 w-5 items-center justify-center rounded-full border border-dashed border-gray-400">
                <UserIcon className="h-3 w-3 text-gray-400" />
              </div>
              <span className="flex-1 text-left">Unassigned</span>
            </>
          )}
        </div>
        <ChevronsUpDown className="ml-2 h-4 w-4 shrink-0 opacity-50" />
      </button>

      {open && (
        <div className="animate-in fade-in-0 zoom-in-95 absolute top-full z-50 mt-2 w-full min-w-[200px] rounded-md border border-gray-200 bg-white shadow-lg duration-100">
          <Command className="w-full overflow-hidden rounded-md">
            <div className="flex items-center border-b px-3">
              <Search className="mr-2 h-4 w-4 shrink-0 opacity-50" />
              <Command.Input
                placeholder="Search member..."
                className="flex h-9 w-full rounded-md bg-transparent py-3 text-sm outline-none placeholder:text-gray-500 disabled:cursor-not-allowed disabled:opacity-50"
              />
            </div>
            <Command.List className="max-h-[300px] overflow-y-auto p-1">
              <Command.Empty className="py-2 text-center text-xs text-gray-500">
                No member found.
              </Command.Empty>

              <Command.Item
                onSelect={() => {
                  onChange(undefined);
                  setOpen(false);
                }}
                className={cn(
                  "relative flex cursor-default items-center rounded-sm px-2 py-2 text-sm outline-none select-none data-[selected=true]:bg-gray-100 data-[selected=true]:text-gray-900",
                  !value && "bg-gray-50 text-gray-900"
                )}
              >
                <div className="mr-2 flex h-5 w-5 shrink-0 items-center justify-center rounded-full border border-dashed border-gray-400">
                  <UserIcon className="h-3 w-3 text-gray-400" />
                </div>
                <span className="flex-1 truncate">Unassigned</span>
                {!value && (
                  <Check className="ml-2 h-4 w-4 shrink-0 text-blue-600" />
                )}
              </Command.Item>

              {members.map((member) => (
                <Command.Item
                  key={member.user_id}
                  onSelect={() => {
                    onChange(member.user_id);
                    setOpen(false);
                  }}
                  className={cn(
                    "relative flex cursor-default items-center rounded-sm px-2 py-2 text-sm outline-none select-none data-[selected=true]:bg-gray-100 data-[selected=true]:text-gray-900",
                    value === member.user_id && "bg-gray-50 text-gray-900"
                  )}
                >
                  <Avatar
                    fallback={member.email[0].toUpperCase()}
                    className="mr-2 h-5 w-5 shrink-0 bg-blue-100 text-[10px]"
                  />
                  <span className="flex-1 truncate">{member.email}</span>
                  {value === member.user_id && (
                    <Check className="ml-2 h-4 w-4 shrink-0 text-blue-600" />
                  )}
                </Command.Item>
              ))}
            </Command.List>
          </Command>
        </div>
      )}
    </div>
  );
}
