// nuxt-app/app/components/project/tabs/Tasks.vue
<script setup lang="ts">
import {
  Plus,
  Search,
  Filter,
  CheckCircle2,
  Circle,
  Loader2,
} from "lucide-vue-next";
import { TaskStatus } from "~/types";

interface Props {
  projectId: number;
}

const { projectId } = defineProps<Props>();

const { tasks, isLoading } = useTasks(projectId);
const statusFilter = ref<"open" | "done">("open");
const searchQuery = ref("");

const openTasks = computed(() =>
  tasks.value.filter((t) => t.status !== TaskStatus.DONE)
);
const doneTasks = computed(() =>
  tasks.value.filter((t) => t.status === TaskStatus.DONE)
);

const displayedTasks = computed(() => {
  const filtered = statusFilter.value === "open" ? openTasks.value : doneTasks.value;
  return filtered.filter((t) =>
    t.title.toLowerCase().includes(searchQuery.value.toLowerCase())
  );
});
</script>

<template>
  <div class="space-y-4">
    <!-- Toolbar -->
    <div class="flex flex-col items-center justify-between gap-4 sm:flex-row">
      <div class="relative w-full sm:w-96">
        <Search class="absolute top-2.5 left-3 h-4 w-4 text-gray-400" />
        <UiBaseInput
          v-model="searchQuery"
          placeholder="Search all tasks"
          class-name="pl-9 border-gray-200 bg-gray-50"
        />
      </div>
      <UiBaseButton @click="navigateTo(`/projects/${projectId}/tasks/new`)">
        <Plus class="mr-2 h-4 w-4" /> New Task
      </UiBaseButton>
    </div>

    <!-- GitHub Style List Container -->
    <div
      class="overflow-hidden rounded-lg border border-gray-200 bg-white shadow-sm"
    >
      <!-- List Header -->
      <div
        class="flex items-center justify-between border-b border-gray-200 bg-gray-50 px-4 py-3"
      >
        <div class="flex items-center gap-4">
          <button
            class="flex items-center gap-1.5 text-sm font-medium transition-colors"
            :class="
              statusFilter === 'open'
                ? 'text-gray-900'
                : 'text-gray-500 hover:text-gray-900'
            "
            @click="statusFilter = 'open'"
          >
            <Circle class="h-4 w-4" />
            {{ openTasks.length }} Open
          </button>
          <button
            class="flex items-center gap-1.5 text-sm font-medium transition-colors"
            :class="
              statusFilter === 'done'
                ? 'text-gray-900'
                : 'text-gray-500 hover:text-gray-900'
            "
            @click="statusFilter = 'done'"
          >
            <CheckCircle2 class="h-4 w-4" />
            {{ doneTasks.length }} Done
          </button>
        </div>

        <div class="flex items-center gap-4 text-sm text-gray-500">
          <button class="flex items-center gap-1 hover:text-gray-900">
            Sort <Filter class="h-3 w-3" />
          </button>
        </div>
      </div>

      <!-- List Content -->
      <div v-if="isLoading" class="flex h-64 items-center justify-center">
        <Loader2 class="h-8 w-8 animate-spin text-gray-400" />
      </div>
      <div v-else class="divide-y divide-gray-100">
        <TasksIssueItem
          v-for="task in displayedTasks"
          :key="task.id"
          :task="task"
          :project-id="projectId"
        />

        <div v-if="displayedTasks.length === 0" class="p-12 text-center">
          <div
            class="mx-auto mb-4 flex h-12 w-12 items-center justify-center text-gray-200"
          >
            <Plus class="h-10 w-10" />
          </div>
          <h3 class="text-lg font-medium text-gray-900">No tasks found</h3>
          <p class="mt-1 text-sm text-gray-500">
            Try adjusting your filters or search query.
          </p>
        </div>
      </div>
    </div>
  </div>
</template>

// frontend/src/app/(dashboard)/tasks/page.tsx
"use client";

import { useState } from "react";
import { useTasks } from "@/hooks/use-tasks";
import { TaskListView } from "@/components/tasks/task-list-view";
import { TaskBoardView } from "@/components/tasks/task-board-view";
import { TaskDialog } from "@/components/tasks/task-dialog";
import { Button } from "@/components/ui/button";
import { LayoutList, Kanban, Plus } from "lucide-react";
import { Task, TaskStatus } from "@/types";

type ViewType = "list" | "board";

export default function TasksPage() {
  const { tasks, isLoading, updateTask } = useTasks();
  const [view, setView] = useState<ViewType>("list");
  
  const [isDialogOpen, setIsDialogOpen] = useState(false);
  const [selectedTask, setSelectedTask] = useState<Task | undefined>(undefined);

  const handleTaskMove = (taskId: number, newStatus: TaskStatus) => {
    updateTask(taskId, { status: newStatus });
  };

  const handleCreateClick = () => {
    setSelectedTask(undefined);
    setIsDialogOpen(true);
  };

  const handleTaskClick = (task: Task) => {
    setSelectedTask(task);
    setIsDialogOpen(true);
  };

  const handleCloseDialog = () => {
    setIsDialogOpen(false);
    setSelectedTask(undefined);
  };

  return (
    <div className="flex flex-col h-full space-y-6">
      <div className="flex items-center justify-between">
        <h1 className="text-2xl font-bold tracking-tight text-gray-900">Tasks</h1>
        <div className="flex items-center gap-2">
            <div className="flex items-center rounded-lg border border-gray-200 bg-white p-1">
                <button
                    onClick={() => setView("list")}
                    className={`rounded-md p-1.5 transition-colors ${view === "list" ? "bg-gray-100 text-gray-900" : "text-gray-500 hover:text-gray-900"}`}
                >
                    <LayoutList className="h-4 w-4" />
                </button>
                <button
                    onClick={() => setView("board")}
                    className={`rounded-md p-1.5 transition-colors ${view === "board" ? "bg-gray-100 text-gray-900" : "text-gray-500 hover:text-gray-900"}`}
                >
                    <Kanban className="h-4 w-4" />
                </button>
            </div>
            <Button onClick={handleCreateClick}>
                <Plus className="mr-2 h-4 w-4" /> Create Task
            </Button>
        </div>
      </div>

      {isLoading ? (
        <div className="flex h-64 items-center justify-center">
            <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-gray-900"></div>
        </div>
      ) : (
        <div className="flex-1 overflow-hidden">
            {view === "list" ? (
                <TaskListView tasks={tasks} onTaskClick={handleTaskClick} />
            ) : (
                <TaskBoardView tasks={tasks} onTaskMove={handleTaskMove} onTaskClick={handleTaskClick} />
            )}
        </div>
      )}

      <TaskDialog 
        isOpen={isDialogOpen} 
        onClose={handleCloseDialog} 
        task={selectedTask}
      />
    </div>
  );
}
