// frontend/app/pages/projects/[projectId]/tasks/new.vue
<script setup lang="ts">
import { ArrowLeft, Loader2, Send } from "lucide-vue-next";
import { TaskStatus, TaskPriority } from "~/types";

definePageMeta({
  layout: "dashboard",
});

const route = useRoute();
const router = useRouter();
const projectId = computed(() => route.params.projectId as string);

const { createTask } = useTasks(projectId.value);
const { members } = useProjectMembers(projectId.value);

const isSaving = ref(false);
const formData = ref({
  title: "",
  description: "",
  status: TaskStatus.TODO,
  priority: TaskPriority.P2,
  assignee_id: null as string | null,
  due_date: "",
});

const handleSubmit = async () => {
  if (!formData.value.title.trim()) return;
  isSaving.value = true;
  try {
    const payload = {
      ...formData.value,
      assignee_id: formData.value.assignee_id || undefined,
      due_date: formData.value.due_date || undefined,
    };
    await createTask(payload);
    router.push(`/projects/${projectId.value}`);
  } catch (err) {
    console.error("Failed to create task", err);
  } finally {
    isSaving.value = false;
  }
};
</script>

<template>
  <div class="mx-auto max-w-4xl space-y-6 pb-20">
    <NuxtLink
      :to="`/projects/${projectId}`"
      class="inline-flex items-center gap-1 text-sm text-gray-500 hover:text-gray-900"
    >
      <ArrowLeft class="h-4 w-4" /> Back to project
    </NuxtLink>

    <div class="flex items-center justify-between">
      <h1 class="text-3xl font-bold text-gray-900">Create New Task</h1>
    </div>

    <div class="grid grid-cols-1 gap-8 lg:grid-cols-3">
      <!-- Main Content -->
      <div class="space-y-6 lg:col-span-2">
        <form class="space-y-6" @submit.prevent="handleSubmit">
          <div class="space-y-2">
            <UiBaseLabel for="title">Title</UiBaseLabel>
            <UiBaseInput
              id="title"
              v-model="formData.title"
              placeholder="What needs to be done?"
              required
              class-name="h-12 text-lg"
              :disabled="isSaving"
            />
          </div>

          <div class="space-y-2">
            <UiBaseLabel for="description">Description</UiBaseLabel>
            <UiBaseMarkdownEditor
              v-model="formData.description"
              placeholder="Add more details... (Markdown supported)"
              :disabled="isSaving"
            />
          </div>

          <div class="flex justify-end gap-3 pt-4">
            <UiBaseButton
              type="button"
              variant="ghost"
              :disabled="isSaving"
              @click="router.back()"
            >
              Cancel
            </UiBaseButton>
            <UiBaseButton
              type="submit"
              class-name="bg-blue-600 px-8 text-white hover:bg-blue-700"
              :disabled="isSaving || !formData.title.trim()"
            >
              <Loader2 v-if="isSaving" class="mr-2 h-4 w-4 animate-spin" />
              <Send v-else class="mr-2 h-4 w-4" />
              Create Task
            </UiBaseButton>
          </div>
        </form>
      </div>

      <!-- Sidebar -->
      <div class="space-y-6 lg:border-l lg:border-gray-100 lg:pl-8">
        <div class="space-y-4">
          <div class="space-y-2">
            <UiBaseLabel>Status</UiBaseLabel>
            <TasksSelectorsStatusSelector v-model="formData.status" />
          </div>

          <div class="space-y-2">
            <UiBaseLabel>Priority</UiBaseLabel>
            <TasksSelectorsPrioritySelector v-model="formData.priority" />
          </div>

          <div class="space-y-2">
            <UiBaseLabel>Assignee</UiBaseLabel>
            <TasksSelectorsAssigneeSelector
              v-model="formData.assignee_id"
              :members="members"
            />
          </div>

          <div class="space-y-2">
            <UiBaseLabel for="due_date">Due Date</UiBaseLabel>
            <UiBaseInput
              id="due_date"
              v-model="formData.due_date"
              type="date"
              :disabled="isSaving"
            />
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

// frontend/src/app/(dashboard)/projects/[projectId]/tasks/new/page.tsx
"use client";

import { use, useState } from "react";
import { useRouter } from "next/navigation";
import { useProjectMembers } from "@/hooks/use-projects";
import { useTasks } from "@/hooks/use-tasks";
import { TaskStatus, TaskPriority } from "@/types";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { MarkdownEditor } from "@/components/ui/markdown-editor";
import { Card, CardContent } from "@/components/ui/card";
import { CheckSquare, ArrowLeft, Loader2 } from "lucide-react";
import Link from "next/link";
import { AssigneeSelector } from "@/components/tasks/selectors/assignee-selector";
import { StatusSelector } from "@/components/tasks/selectors/status-selector";
import { PrioritySelector } from "@/components/tasks/selectors/priority-selector";

export default function NewTaskPage({
  params,
}: {
  params: Promise<{ projectId: string }>;
}) {
  const resolvedParams = use(params);
  const projectId = parseInt(resolvedParams.projectId);
  const router = useRouter();

  const { createTask } = useTasks(projectId);
  const { members } = useProjectMembers(projectId);

  const [title, setTitle] = useState("");
  const [description, setDescription] = useState("");
  const [status, setStatus] = useState<TaskStatus>(TaskStatus.TODO);
  const [priority, setPriority] = useState<TaskPriority>(TaskPriority.P2);
  const [assigneeId, setAssigneeId] = useState<number | undefined>(undefined);
  const [dueDate, setDueDate] = useState<string | undefined>(undefined);
  const [isSubmitting, setIsSubmitting] = useState(false);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!title.trim()) return;

    setIsSubmitting(true);
    try {
      await createTask({
        title,
        description,
        status,
        priority,
        assignee_id: assigneeId,
        due_date: dueDate,
      });
      router.push(`/projects/${projectId}`);
    } catch (error) {
      console.error(error);
      alert("Failed to create task");
    } finally {
      setIsSubmitting(false);
    }
  };

  return (
    <div className="mx-auto max-w-5xl space-y-6">
      <div className="flex items-center gap-4">
        <Link
          href={`/projects/${projectId}`}
          className="rounded-full p-2 transition-colors hover:bg-gray-100"
        >
          <ArrowLeft className="h-5 w-5 text-gray-500" />
        </Link>
        <h1 className="flex items-center gap-2 text-2xl font-bold text-gray-900">
          <CheckSquare className="h-6 w-6 text-blue-600" />
          Create new task
        </h1>
      </div>

      <form
        onSubmit={handleSubmit}
        className="grid grid-cols-1 gap-8 lg:grid-cols-4"
      >
        {/* Main Content */}
        <div className="space-y-6 lg:col-span-3">
          <Card className="border-gray-200">
            <CardContent className="space-y-4 p-6">
              <div className="space-y-2">
                <Label htmlFor="title" className="text-sm font-semibold">
                  Title
                </Label>
                <Input
                  id="title"
                  placeholder="Task title"
                  value={title}
                  onChange={(e) => setTitle(e.target.value)}
                  className="h-12 text-lg focus-visible:ring-blue-500"
                  required
                />
              </div>
              <div className="space-y-2">
                <Label className="text-sm font-semibold">Description</Label>
                <MarkdownEditor
                  value={description}
                  onChange={setDescription}
                  placeholder="Add a description..."
                />
              </div>
            </CardContent>
          </Card>

          <div className="flex justify-end gap-3">
            <Button type="button" variant="ghost" onClick={() => router.back()}>
              Cancel
            </Button>
            <Button
              type="submit"
              disabled={isSubmitting || !title.trim()}
              className="px-8"
            >
              {isSubmitting && (
                <Loader2 className="mr-2 h-4 w-4 animate-spin" />
              )}
              Submit New Task
            </Button>
          </div>
        </div>

        {/* Sidebar */}
        <div className="space-y-6 lg:col-span-1">
          <Card className="border-gray-200 shadow-none">
            <CardContent className="space-y-6 p-4">
              <div className="space-y-2 border-b border-gray-100 pb-4">
                <Label className="text-xs font-bold tracking-wider text-gray-500 uppercase">
                  Due Date
                </Label>
                <Input
                  type="date"
                  value={dueDate || ""}
                  onChange={(e) => setDueDate(e.target.value || undefined)}
                />
              </div>

              <div className="space-y-2 border-b border-gray-100 pb-4">
                <Label className="text-xs font-bold tracking-wider text-gray-500 uppercase">
                  Assignee
                </Label>
                <AssigneeSelector
                  members={members}
                  value={assigneeId}
                  onChange={setAssigneeId}
                />
              </div>

              <div className="space-y-2 border-b border-gray-100 pb-4">
                <Label className="text-xs font-bold tracking-wider text-gray-500 uppercase">
                  Status
                </Label>
                <StatusSelector value={status} onChange={setStatus} />
              </div>

              <div className="space-y-2">
                <Label className="text-xs font-bold tracking-wider text-gray-500 uppercase">
                  Priority
                </Label>
                <PrioritySelector value={priority} onChange={setPriority} />
              </div>
            </CardContent>
          </Card>
        </div>
      </form>
    </div>
  );
}
