// frontend/src/app/(dashboard)/dashboard/page.tsx
"use client";

import Link from "next/link";
import useSWR from "swr";
import { format } from "date-fns";
import {
  Folder,
  Users,
  CheckSquare,
  Plus,
  ArrowRight,
  Activity,
  Briefcase,
} from "lucide-react";

import api from "@/lib/api";
import { cn } from "@/lib/utils";
import { useUser } from "@/hooks/use-user";
import { useWorkspaces } from "@/hooks/use-workspaces";
import { useProjects } from "@/hooks/use-projects";
import { useMyTasks } from "@/hooks/use-my-tasks";
import { WorkspaceMember, TaskStatus } from "@/types";

import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { TaskDialog } from "@/components/tasks/task-dialog";
import { useState } from "react";

const fetcher = (url: string) => api.get(url).then((res) => res.data);

export default function DashboardPage() {
  const { user } = useUser();
  const { activeWorkspace } = useWorkspaces();
  const { projects, isLoading: projectsLoading } = useProjects();
  const { tasks: myTasks, isLoading: tasksLoading } = useMyTasks();

  // Fetch members for stats
  const { data: members } = useSWR<WorkspaceMember[]>(
    activeWorkspace ? `/api/v1/workspaces/${activeWorkspace.id}/members` : null,
    fetcher
  );

  const [isTaskDialogOpen, setIsTaskDialogOpen] = useState(false);

  // Filter tasks for this workspace (since /me returns all)
  // Assuming MyTasks API might return workspace_id in the future, currently we filter by project which has workspace_id
  // Actually, TaskWithProject has `project: { id, name }`.
  // We need to know which workspace the project belongs to.
  // The current API might not return workspace_id for the project in /tasks/me.
  // Optimization: Just show "My Tasks" generally or filter if we can match project IDs with `projects` list.
  const workspaceProjectIds = new Set(projects.map((p) => p.id));
  const workspaceTasks = myTasks.filter((t) =>
    workspaceProjectIds.has(t.project_id)
  );

  const pendingTasksCount = workspaceTasks.filter(
    (t) => t.status !== TaskStatus.DONE
  ).length;
  const recentTasks = workspaceTasks
    .filter((t) => t.status !== TaskStatus.DONE)
    .sort((a, b) => {
      // Sort by priority (P0 > P1...) then due date
      if (a.priority !== b.priority)
        return a.priority.localeCompare(b.priority);
      return (
        new Date(a.due_date || "2100-01-01").getTime() -
        new Date(b.due_date || "2100-01-01").getTime()
      );
    })
    .slice(0, 5);

  const getTimeGreeting = () => {
    const hour = new Date().getHours();
    if (hour < 12) return "Good morning";
    if (hour < 18) return "Good afternoon";
    return "Good evening";
  };

  return (
    <div className="space-y-8">
      {/* Header */}
      <div className="flex flex-col gap-1 sm:flex-row sm:items-center sm:justify-between">
        <div>
          <h1 className="text-2xl font-bold text-gray-900">
            {getTimeGreeting()}, {user?.full_name?.split(" ")[0] || "there"}
          </h1>
          <p className="text-gray-500">
            Here&apos;s what&apos;s happening in{" "}
            <span className="font-medium text-gray-900">
              {activeWorkspace?.name}
            </span>{" "}
            today.
          </p>
        </div>
        <div className="mt-4 flex gap-2 sm:mt-0">
          <Button
            onClick={() => setIsTaskDialogOpen(true)}
            size="sm"
            className="hidden sm:flex"
            disabled={projects.length === 0}
            title={
              projects.length === 0
                ? "Create a project first"
                : "Create a new task"
            }
          >
            <Plus className="mr-2 h-4 w-4" /> New Task
          </Button>
          <TaskDialog
            isOpen={isTaskDialogOpen}
            onClose={() => setIsTaskDialogOpen(false)}
            projectId={projects[0]?.id} // Default to first project if any
          />
        </div>
      </div>

      {/* Stats Grid */}
      <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-4">
        <StatsCard
          title="Active Projects"
          value={projects.filter((p) => !p.is_archived).length}
          icon={Folder}
          isLoading={projectsLoading}
          color="blue"
        />
        <StatsCard
          title="Team Members"
          value={members?.length || 0}
          icon={Users}
          isLoading={!members}
          color="indigo"
        />
        <StatsCard
          title="Pending Tasks"
          value={pendingTasksCount}
          icon={CheckSquare}
          isLoading={tasksLoading}
          color="orange"
        />
        <StatsCard
          title="Workspace Activity"
          value="Unknown" // Placeholder for now
          label="Last 7 days"
          icon={Activity}
          isLoading={false}
          color="green"
        />
      </div>

      <div className="grid grid-cols-1 gap-8 lg:grid-cols-3">
        {/* Main Column: Projects */}
        <div className="space-y-6 lg:col-span-2">
          <div className="flex items-center justify-between">
            <h2 className="text-lg font-semibold text-gray-900">
              Recent Projects
            </h2>
            <Link
              href="/projects/new"
              className="text-sm font-medium text-blue-600 hover:text-blue-700"
            >
              View all
            </Link>
          </div>

          {projectsLoading ? (
            <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
              {[1, 2, 3, 4].map((i) => (
                <SkeletonCard key={i} />
              ))}
            </div>
          ) : projects.length === 0 ? (
            <div className="rounded-lg border-2 border-dashed border-gray-200 bg-gray-50 p-8 text-center">
              <div className="mx-auto flex h-12 w-12 items-center justify-center rounded-full bg-gray-100">
                <Briefcase className="h-6 w-6 text-gray-400" />
              </div>
              <h3 className="mt-2 text-sm font-semibold text-gray-900">
                No projects
              </h3>
              <p className="mt-1 text-sm text-gray-500">
                Get started by creating a new project.
              </p>
              <div className="mt-6">
                {/* This would be the ProjectDialog trigger usually */}
                <Button variant="outline" size="sm">
                  Create Project
                </Button>
              </div>
            </div>
          ) : (
            <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
              {projects.slice(0, 4).map((project) => (
                <Link
                  key={project.id}
                  href={`/projects/${project.id}`}
                  className="block h-full"
                >
                  <Card className="group h-full cursor-pointer border-gray-200 p-5 transition-shadow hover:border-blue-200 hover:shadow-md">
                    <div className="mb-4 flex items-start justify-between">
                      <div className="rounded-lg bg-blue-50 p-2 transition-colors group-hover:bg-blue-100">
                        <Folder className="h-5 w-5 text-blue-600" />
                      </div>
                      {project.is_archived && (
                        <Badge variant="secondary">Archived</Badge>
                      )}
                    </div>
                    <h3 className="mb-1 font-semibold text-gray-900 transition-colors group-hover:text-blue-700">
                      {project.name}
                    </h3>
                    <p className="line-clamp-2 text-sm text-gray-500">
                      {project.description || "No description provided."}
                    </p>
                    <div className="mt-4 flex items-center justify-between border-t border-gray-100 pt-4 text-xs text-gray-500">
                      <span>
                        Updated {format(new Date(project.created_at), "MMM d")}
                      </span>
                      <ArrowRight className="h-3 w-3 transform opacity-0 transition-opacity group-hover:translate-x-1 group-hover:opacity-100" />
                    </div>
                  </Card>
                </Link>
              ))}
            </div>
          )}
        </div>

        {/* Side Column: My Tasks */}
        <div className="space-y-6">
          <div className="flex items-center justify-between">
            <h2 className="text-lg font-semibold text-gray-900">
              My Priorities
            </h2>
            <Link
              href="/inbox"
              className="text-sm font-medium text-blue-600 hover:text-blue-700"
            >
              Go to Inbox
            </Link>
          </div>

          <div className="space-y-3">
            {tasksLoading ? (
              <div className="space-y-3">
                {[1, 2, 3].map((i) => (
                  <div
                    key={i}
                    className="h-16 animate-pulse rounded-lg bg-gray-100"
                  />
                ))}
              </div>
            ) : recentTasks.length === 0 ? (
              <div className="rounded-lg border border-gray-200 bg-gray-50 p-6 text-center">
                <p className="text-sm text-gray-500">
                  No pending tasks in this workspace.
                </p>
              </div>
            ) : (
              recentTasks.map((task) => (
                <div
                  key={task.id}
                  className="group flex items-start gap-3 rounded-lg border border-gray-200 bg-white p-3 transition-all hover:border-blue-200 hover:shadow-sm"
                >
                  <div
                    className={cn(
                      "mt-0.5 h-2 w-2 flex-shrink-0 rounded-full",
                      task.priority === "P0"
                        ? "bg-red-500"
                        : task.priority === "P1"
                          ? "bg-orange-500"
                          : "bg-blue-500"
                    )}
                  />
                  <div className="min-w-0 flex-1">
                    <p className="truncate text-sm font-medium text-gray-900">
                      {task.title}
                    </p>
                    <div className="mt-1 flex items-center gap-2">
                      <span className="text-[10px] tracking-wider text-gray-500 uppercase">
                        {task.project?.name}
                      </span>
                      {task.due_date && (
                        <span className="text-[10px] text-gray-400">
                          {format(new Date(task.due_date), "MMM d")}
                        </span>
                      )}
                    </div>
                  </div>
                </div>
              ))
            )}

            {workspaceTasks.length > 5 && (
              <Link
                href="/inbox"
                className="mt-2 block text-center text-xs text-gray-500 hover:text-gray-900"
              >
                + {workspaceTasks.length - 5} more tasks
              </Link>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}

interface StatsCardProps {
  title: string;
  value: number | string;
  icon: React.ElementType;
  isLoading: boolean;
  color: "blue" | "indigo" | "orange" | "green";
  label?: string;
}

function StatsCard({
  title,
  value,
  icon: Icon,
  isLoading,
  color,
  label,
}: StatsCardProps) {
  const colors: Record<string, string> = {
    blue: "bg-blue-50 text-blue-600",
    indigo: "bg-indigo-50 text-indigo-600",
    orange: "bg-orange-50 text-orange-600",
    green: "bg-green-50 text-green-600",
  };

  return (
    <Card className="border-gray-200 p-5 shadow-sm">
      <div className="flex items-center justify-between">
        <div>
          <p className="text-sm font-medium text-gray-500">{title}</p>
          {isLoading ? (
            <div className="mt-1 h-8 w-16 animate-pulse rounded bg-gray-100" />
          ) : (
            <div className="mt-1 flex items-baseline gap-2">
              <span className="text-2xl font-bold text-gray-900">{value}</span>
              {label && (
                <span className="text-xs font-normal text-gray-500">
                  {label}
                </span>
              )}
            </div>
          )}
        </div>
        <div className={cn("rounded-lg p-2", colors[color] || colors.blue)}>
          <Icon className="h-5 w-5" />
        </div>
      </div>
    </Card>
  );
}

function SkeletonCard() {
  return (
    <div className="h-40 animate-pulse rounded-lg border border-gray-200 bg-gray-100" />
  );
}

// frontend/app/pages/dashboard/index.vue
<script setup lang="ts">
import {
  Folder,
  Users,
  CheckSquare,
  Plus,
  ArrowRight,
  Activity,
  Briefcase,
} from "lucide-vue-next";
import { format } from "date-fns";
import { TaskStatus, type WorkspaceMember } from "~/types";
import { useUsersStore } from "~/stores/user";

definePageMeta({
  layout: "dashboard",
});

const userStore = useUsersStore();
const user = computed(() => userStore.userData);
const { activeWorkspace } = useWorkspaces();
const { projects, isLoading: projectsLoading } = useProjects();
const { tasks: myTasks, isLoading: tasksLoading } = useMyTasks();

// Fetch members for stats
const { data: members } = useApi<WorkspaceMember[]>(
  () =>
    activeWorkspace.value
      ? `/api/v2/workspaces/${activeWorkspace.value.id}/members`
      : "/api/v2/workspaces/0/members",
  {
    key: "workspace-members",
    watch: [activeWorkspace],
  }
);

const isTaskDialogOpen = ref(false);

const workspaceProjectIds = computed(
  () => new Set(projects.value.map((p) => p.id))
);
const workspaceTasks = computed(() =>
  myTasks.value.filter((t) => workspaceProjectIds.value.has(t.project_id))
);

const pendingTasksCount = computed(
  () => workspaceTasks.value.filter((t) => t.status !== TaskStatus.DONE).length
);

const recentTasks = computed(() =>
  [...workspaceTasks.value]
    .filter((t) => t.status !== TaskStatus.DONE)
    .sort((a, b) => {
      if (a.priority !== b.priority)
        return a.priority.localeCompare(b.priority);
      return (
        new Date(a.due_date || "2100-01-01").getTime() -
        new Date(b.due_date || "2100-01-01").getTime()
      );
    })
    .slice(0, 5)
);

const getTimeGreeting = () => {
  const hour = new Date().getHours();
  if (hour < 12) return "Good morning";
  if (hour < 18) return "Good afternoon";
  return "Good evening";
};
</script>

<template>
  <div class="space-y-8">
    <!-- Header -->
    <div
      class="flex flex-col gap-1 sm:flex-row sm:items-center sm:justify-between"
    >
      <div>
        <h1 class="text-2xl font-bold text-gray-900">
          {{ getTimeGreeting() }},
          {{ user?.full_name?.split(" ")[0] || "there" }}
        </h1>
        <p class="text-gray-500">
          Here's what's happening in
          <span class="font-medium text-gray-900">
            {{ activeWorkspace?.name }}
          </span>
          today.
        </p>
      </div>
      <div class="mt-4 flex gap-2 sm:mt-0">
        <UiBaseButton
          size="sm"
          class="hidden sm:flex"
          :disabled="projects.length === 0"
          :title="
            projects.length === 0
              ? 'Create a project first'
              : 'Create a new task'
          "
          @click="isTaskDialogOpen = true"
        >
          <Plus class="mr-2 h-4 w-4" /> New Task
        </UiBaseButton>
      </div>
    </div>

    <!-- Stats Grid -->
    <div class="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-4">
      <DashboardStatsCard
        title="Active Projects"
        :value="projects.filter((p) => !p.is_archived).length"
        :icon="Folder"
        :is-loading="projectsLoading"
        color="blue"
      />
      <DashboardStatsCard
        title="Team Members"
        :value="members?.length || 0"
        :icon="Users"
        :is-loading="!members"
        color="indigo"
      />
      <DashboardStatsCard
        title="Pending Tasks"
        :value="pendingTasksCount"
        :icon="CheckSquare"
        :is-loading="tasksLoading"
        color="orange"
      />
      <DashboardStatsCard
        title="Workspace Activity"
        value="Unknown"
        label="Last 7 days"
        :icon="Activity"
        :is-loading="false"
        color="green"
      />
    </div>

    <div class="grid grid-cols-1 gap-8 lg:grid-cols-3">
      <!-- Main Column: Projects -->
      <div class="space-y-6 lg:col-span-2">
        <div class="flex items-center justify-between">
          <h2 class="text-lg font-semibold text-gray-900">Recent Projects</h2>
          <NuxtLink
            to="/projects"
            class="text-sm font-medium text-blue-600 hover:text-blue-700"
          >
            View all
          </NuxtLink>
        </div>

        <div
          v-if="projectsLoading"
          class="grid grid-cols-1 gap-4 sm:grid-cols-2"
        >
          <div
            v-for="i in 4"
            :key="i"
            class="h-40 animate-pulse rounded-lg border border-gray-200 bg-gray-100"
          />
        </div>
        <div
          v-else-if="projects.length === 0"
          class="rounded-lg border-2 border-dashed border-gray-200 bg-gray-50 p-8 text-center"
        >
          <div
            class="mx-auto flex h-12 w-12 items-center justify-center rounded-full bg-gray-100"
          >
            <Briefcase class="h-6 w-6 text-gray-400" />
          </div>
          <h3 class="mt-2 text-sm font-semibold text-gray-900">No projects</h3>
          <p class="mt-1 text-sm text-gray-500">
            Get started by creating a new project.
          </p>
          <div class="mt-6">
            <UiBaseButton variant="outline" size="sm">
              Create Project
            </UiBaseButton>
          </div>
        </div>
        <div v-else class="grid grid-cols-1 gap-4 sm:grid-cols-2">
          <NuxtLink
            v-for="project in projects.slice(0, 4)"
            :key="project.id"
            :to="`/projects/${project.id}`"
            class="block h-full"
          >
            <UiBaseCard
              class="group h-full cursor-pointer border-gray-200 p-5 transition-shadow hover:border-blue-200 hover:shadow-md"
            >
              <div class="mb-4 flex items-start justify-between">
                <div
                  class="rounded-lg bg-blue-50 p-2 transition-colors group-hover:bg-blue-100"
                >
                  <Folder class="h-5 w-5 text-blue-600" />
                </div>
                <UiBaseBadge v-if="project.is_archived" variant="secondary">
                  Archived
                </UiBaseBadge>
              </div>
              <h3
                class="mb-1 font-semibold text-gray-900 transition-colors group-hover:text-blue-700"
              >
                {{ project.name }}
              </h3>
              <p class="line-clamp-2 text-sm text-gray-500">
                {{ project.description || "No description provided." }}
              </p>
              <div
                class="mt-4 flex items-center justify-between border-t border-gray-100 pt-4 text-xs text-gray-500"
              >
                <span>
                  Updated {{ format(new Date(project.created_at), "MMM d") }}
                </span>
                <ArrowRight
                  class="h-3 w-3 transform opacity-0 transition-opacity group-hover:translate-x-1 group-hover:opacity-100"
                />
              </div>
            </UiBaseCard>
          </NuxtLink>
        </div>
      </div>

      <!-- Side Column: My Tasks -->
      <div class="space-y-6">
        <div class="flex items-center justify-between">
          <h2 class="text-lg font-semibold text-gray-900">My Priorities</h2>
          <NuxtLink
            to="/inbox"
            class="text-sm font-medium text-blue-600 hover:text-blue-700"
          >
            Go to Inbox
          </NuxtLink>
        </div>

        <div class="space-y-3">
          <div v-if="tasksLoading" class="space-y-3">
            <div
              v-for="i in 3"
              :key="i"
              class="h-16 animate-pulse rounded-lg bg-gray-100"
            />
          </div>
          <div
            v-else-if="recentTasks.length === 0"
            class="rounded-lg border border-gray-200 bg-gray-50 p-6 text-center"
          >
            <p class="text-sm text-gray-500">
              No pending tasks in this workspace.
            </p>
          </div>
          <template v-else>
            <div
              v-for="task in recentTasks"
              :key="task.id"
              class="group flex items-start gap-3 rounded-lg border border-gray-200 bg-white p-3 transition-all hover:border-blue-200 hover:shadow-sm"
            >
              <div
                class="mt-0.5 h-2 w-2 flex-shrink-0 rounded-full"
                :class="
                  task.priority === 'P0'
                    ? 'bg-red-500'
                    : task.priority === 'P1'
                      ? 'bg-orange-500'
                      : 'bg-blue-500'
                "
              />
              <div class="min-w-0 flex-1">
                <p class="truncate text-sm font-medium text-gray-900">
                  {{ task.title }}
                </p>
                <div class="mt-1 flex items-center gap-2">
                  <span
                    class="text-[10px] tracking-wider text-gray-500 uppercase"
                  >
                    {{ task.project?.name || `Project #${task.project_id}` }}
                  </span>
                  <span v-if="task.due_date" class="text-[10px] text-gray-400">
                    {{ format(new Date(task.due_date), "MMM d") }}
                  </span>
                </div>
              </div>
            </div>
          </template>

          <NuxtLink
            v-if="workspaceTasks.length > 5"
            to="/inbox"
            class="mt-2 block text-center text-xs text-gray-500 hover:text-gray-900"
          >
            + {{ workspaceTasks.length - 5 }} more tasks
          </NuxtLink>
        </div>
      </div>
    </div>

    <!-- Task Dialog Placeholder -->
    <div v-if="isTaskDialogOpen" class="hidden">
      <!-- To be implemented -->
    </div>
  </div>
</template>
