// frontend/src/components/layout/command-palette.tsx
"use client";

import * as React from "react";
import { useRouter } from "next/navigation";
import { Command } from "cmdk";
import {
  Inbox,
  Plus,
  LayoutDashboard,
  Search,
  CheckSquare,
  Building2,
} from "lucide-react";
import { useWorkspaces } from "@/hooks/use-workspaces";
import { useWorkspaceStore } from "@/store/workspace-store";
import { TaskDialog } from "@/components/tasks/task-dialog";

export function CommandPalette() {
  const [open, setOpen] = React.useState(false);
  const [showTaskDialog, setShowTaskDialog] = React.useState(false);
  const router = useRouter();
  const { workspaces } = useWorkspaces();
  const { setActiveWorkspaceId } = useWorkspaceStore();

  // Toggle the menu when ⌘K is pressed
  React.useEffect(() => {
    const down = (e: KeyboardEvent) => {
      if (e.key === "k" && (e.metaKey || e.ctrlKey)) {
        e.preventDefault();
        setOpen((open) => !open);
      }
      if (e.key === "Escape") {
        setOpen(false);
      }
    };

    document.addEventListener("keydown", down);
    return () => document.removeEventListener("keydown", down);
  }, []);

  const runCommand = React.useCallback((command: () => void) => {
    setOpen(false);
    command();
  }, []);

  if (!open)
    return (
      <TaskDialog
        isOpen={showTaskDialog}
        onClose={() => setShowTaskDialog(false)}
      />
    );

  return (
    <>
      <div
        className="animate-in fade-in fixed inset-0 z-50 flex items-start justify-center bg-black/50 p-4 pt-[20vh] backdrop-blur-sm duration-200"
        onClick={() => setOpen(false)}
      >
        <Command
          className="animate-in zoom-in-95 w-full max-w-[640px] overflow-hidden rounded-xl border border-gray-200 bg-white shadow-2xl duration-200"
          onClick={(e) => e.stopPropagation()}
        >
          <div className="flex items-center border-b px-3">
            <Search className="mr-2 h-4 w-4 shrink-0 text-gray-400" />
            <Command.Input
              placeholder="Type a command or search..."
              className="flex h-12 w-full rounded-md bg-transparent py-3 text-sm outline-none placeholder:text-gray-400 disabled:cursor-not-allowed disabled:opacity-50"
            />
          </div>
          <Command.List className="max-h-[300px] overflow-y-auto p-2">
            <Command.Empty className="py-6 text-center text-sm text-gray-500">
              No results found.
            </Command.Empty>

            <Command.Group
              heading="Navigation"
              className="px-2 py-1.5 text-xs font-semibold tracking-wider text-gray-500 uppercase"
            >
              <Command.Item
                onSelect={() => runCommand(() => router.push("/inbox"))}
                className="flex cursor-pointer items-center rounded-md px-2 py-2 text-sm text-gray-700 outline-none aria-selected:bg-blue-50 aria-selected:text-blue-600"
              >
                <Inbox className="mr-3 h-4 w-4" />
                Go to Inbox
              </Command.Item>
              <Command.Item
                onSelect={() => runCommand(() => router.push("/tasks"))}
                className="flex cursor-pointer items-center rounded-md px-2 py-2 text-sm text-gray-700 outline-none aria-selected:bg-blue-50 aria-selected:text-blue-600"
              >
                <CheckSquare className="mr-3 h-4 w-4" />
                All Tasks
              </Command.Item>
              <Command.Item
                onSelect={() => runCommand(() => router.push("/dashboard"))}
                className="flex cursor-pointer items-center rounded-md px-2 py-2 text-sm text-gray-700 outline-none aria-selected:bg-blue-50 aria-selected:text-blue-600"
              >
                <LayoutDashboard className="mr-3 h-4 w-4" />
                Dashboard
              </Command.Item>
            </Command.Group>

            <Command.Group
              heading="Actions"
              className="mt-2 px-2 py-1.5 text-xs font-semibold tracking-wider text-gray-500 uppercase"
            >
              <Command.Item
                onSelect={() => runCommand(() => setShowTaskDialog(true))}
                className="flex cursor-pointer items-center rounded-md px-2 py-2 text-sm text-gray-700 outline-none aria-selected:bg-blue-50 aria-selected:text-blue-600"
              >
                <Plus className="mr-3 h-4 w-4" />
                Create New Task
              </Command.Item>
            </Command.Group>

            <Command.Group
              heading="Workspaces"
              className="mt-2 px-2 py-1.5 text-xs font-semibold tracking-wider text-gray-500 uppercase"
            >
              {workspaces.map((workspace) => (
                <Command.Item
                  key={workspace.id}
                  onSelect={() =>
                    runCommand(() => {
                      setActiveWorkspaceId(workspace.id);
                      router.push("/dashboard");
                    })
                  }
                  className="flex cursor-pointer items-center rounded-md px-2 py-2 text-sm text-gray-700 outline-none aria-selected:bg-blue-50 aria-selected:text-blue-600"
                >
                  <Building2 className="mr-3 h-4 w-4" />
                  Switch to {workspace.name}
                </Command.Item>
              ))}
            </Command.Group>
          </Command.List>

          <div className="flex items-center justify-end border-t bg-gray-50 px-3 py-2">
            <p className="text-[10px] text-gray-400">
              Press <kbd className="font-sans text-gray-500">esc</kbd> to close
            </p>
          </div>
        </Command>
      </div>

      <TaskDialog
        isOpen={showTaskDialog}
        onClose={() => setShowTaskDialog(false)}
      />
    </>
  );
}

// frontend/app/components/layout/CommandPalette.vue
<script setup lang="ts">
import {
  TransitionRoot,
  TransitionChild,
  Dialog,
  DialogPanel,
  Combobox,
  ComboboxInput,
  ComboboxOptions,
  ComboboxOption,
} from "@headlessui/vue";
import {
  Search,
  Inbox,
  CheckSquare,
  LayoutDashboard,
  Building2,
} from "lucide-vue-next";
import type { Component } from "vue";
import type { Workspace } from "~/types";

const isOpen = ref(false);
const query = ref("");
const router = useRouter();
const workspaceStore = useWorkspaceStore();
const { workspaces } = useWorkspaces();

// Toggle the menu when ⌘K is pressed
const onKeyDown = (e: KeyboardEvent) => {
  if (e.key === "k" && (e.metaKey || e.ctrlKey)) {
    e.preventDefault();
    isOpen.value = !isOpen.value;
  }
};

onMounted(() => {
  window.addEventListener("keydown", onKeyDown);
});

onUnmounted(() => {
  window.removeEventListener("keydown", onKeyDown);
});

interface NavItem {
  name: string;
  href: string;
  icon: Component;
}

const navigation: NavItem[] = [
  { name: "Go to Inbox", href: "/inbox", icon: Inbox },
  { name: "All Tasks", href: "/tasks", icon: CheckSquare },
  { name: "Dashboard", href: "/dashboard", icon: LayoutDashboard },
];

const filteredNavigation = computed(() =>
  query.value === ""
    ? navigation
    : navigation.filter((item) =>
        item.name.toLowerCase().includes(query.value.toLowerCase())
      )
);

const filteredWorkspaces = computed(() =>
  query.value === ""
    ? workspaces.value
    : workspaces.value.filter((w) =>
        w.name.toLowerCase().includes(query.value.toLowerCase())
      )
);

const runCommand = (action: () => void) => {
  isOpen.value = false;
  action();
};

const handleSelect = (item: NavItem | Workspace) => {
  if ("href" in item) {
    runCommand(() => router.push(item.href));
  } else if ("id" in item) {
    // Workspace selection
    runCommand(() => {
      workspaceStore.setActiveWorkspaceId(item.id);
      router.push("/dashboard");
    });
  }
};
</script>

<template>
  <TransitionRoot :show="isOpen" as="template" appear>
    <Dialog as="div" class="relative z-50" @close="isOpen = false">
      <TransitionChild
        as="template"
        enter="duration-300 ease-out"
        enter-from="opacity-0"
        enter-to="opacity-100"
        leave="duration-200 ease-in"
        leave-from="opacity-100"
        leave-to="opacity-0"
      >
        <div
          class="fixed inset-0 bg-black/50 backdrop-blur-sm transition-opacity"
        />
      </TransitionChild>

      <div class="fixed inset-0 z-10 overflow-y-auto p-4 sm:p-6 md:p-20">
        <TransitionChild
          as="template"
          enter="duration-300 ease-out"
          enter-from="opacity-0 scale-95"
          enter-to="opacity-100 scale-100"
          leave="duration-200 ease-in"
          leave-from="opacity-100 scale-100"
          leave-to="opacity-0 scale-95"
        >
          <DialogPanel
            class="mx-auto max-w-2xl transform divide-y divide-gray-100 overflow-hidden rounded-xl bg-white shadow-2xl ring-1 ring-black/5 transition-all"
          >
            <Combobox @update:model-value="handleSelect">
              <div class="relative">
                <Search
                  class="pointer-events-none absolute top-3.5 left-4 h-5 w-5 text-gray-400"
                  aria-hidden="true"
                />
                <ComboboxInput
                  class="h-12 w-full border-0 bg-transparent pr-4 pl-11 text-gray-900 outline-none placeholder:text-gray-400 focus:ring-0 sm:text-sm"
                  placeholder="Search..."
                  @change="query = $event.target.value"
                />
              </div>

              <ComboboxOptions
                v-if="
                  filteredNavigation.length > 0 || filteredWorkspaces.length > 0
                "
                static
                class="max-h-80 scroll-py-2 divide-y divide-gray-100 overflow-y-auto"
              >
                <li class="p-2">
                  <h2
                    v-if="filteredNavigation.length > 0"
                    class="mt-4 mb-2 px-3 text-xs font-semibold tracking-wider text-gray-500 uppercase"
                  >
                    Navigation
                  </h2>
                  <ComboboxOption
                    v-for="item in filteredNavigation"
                    :key="item.href"
                    v-slot="{ active }"
                    :value="item"
                    as="template"
                  >
                    <div
                      :class="[
                        'flex cursor-default items-center rounded-md px-3 py-2 transition-colors select-none',
                        active ? 'bg-blue-600 text-white' : 'text-gray-700',
                      ]"
                    >
                      <component
                        :is="item.icon"
                        :class="[
                          'h-5 w-5 flex-none',
                          active ? 'text-white' : 'text-gray-400',
                        ]"
                        aria-hidden="true"
                      />
                      <span class="ml-3 flex-auto truncate">{{
                        item.name
                      }}</span>
                    </div>
                  </ComboboxOption>
                </li>

                <li v-if="filteredWorkspaces.length > 0" class="p-2">
                  <h2
                    class="mt-4 mb-2 px-3 text-xs font-semibold tracking-wider text-gray-500 uppercase"
                  >
                    Workspaces
                  </h2>
                  <ComboboxOption
                    v-for="workspace in filteredWorkspaces"
                    :key="workspace.id"
                    v-slot="{ active }"
                    :value="workspace"
                    as="template"
                  >
                    <div
                      :class="[
                        'flex cursor-default items-center rounded-md px-3 py-2 transition-colors select-none',
                        active ? 'bg-blue-600 text-white' : 'text-gray-700',
                      ]"
                    >
                      <Building2
                        :class="[
                          'h-5 w-5 flex-none',
                          active ? 'text-white' : 'text-gray-400',
                        ]"
                        aria-hidden="true"
                      />
                      <span class="ml-3 flex-auto truncate">{{
                        workspace.name
                      }}</span>
                    </div>
                  </ComboboxOption>
                </li>
              </ComboboxOptions>

              <div
                v-if="
                  query !== '' &&
                  filteredNavigation.length === 0 &&
                  filteredWorkspaces.length === 0
                "
                class="px-6 py-14 text-center sm:px-14"
              >
                <Search
                  class="mx-auto h-6 w-6 text-gray-400"
                  aria-hidden="true"
                />
                <p class="mt-4 text-sm text-gray-900">
                  No results found for "{{ query }}".
                </p>
              </div>
            </Combobox>
          </DialogPanel>
        </TransitionChild>
      </div>
    </Dialog>
  </TransitionRoot>
</template>
